apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: navyashree47/shopflix-product-service:e128c5486fd12149849300a71830907ad7b2ec1e
          ports:
            - containerPort: 8000